apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-react-app
  labels:
    app: {{ .Release.Name }}-react-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-react-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-react-app
    spec:
      containers:
      - name: react-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000

