replicaCount: 1

image:
  repository: web-app
  tag: "2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # tls:
  #   - secretName: chart-example-tls
  #     hosts:
  #       - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

